site_name: Vox AI | Documentação Técnica

theme:
  name: material
  language: pt-BR
  logo: assets/rainbow.png
  favicon: assets/rainbow.png
  features:
    - navigation.sections

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: red
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo noturno

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: red
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro

markdown_extensions:
  - toc:
      toc_depth: 5
      permalink: true

copyright: "© Vox AI: conversas que importam | Licença GNU GPLv3"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/emn-f/vox-ai
      name: Repositório Principal

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/projetovoxai/

    - icon: material/link-variant
      link: https://linktr.ee/vox_ai
      name: Linktree do Projeto

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/assistentevox/
      name: Vox no LinkedIn
      
    - icon: fontawesome/brands/medium
      link: https://medium.com/@emnferreira/do-mvp-ao-rag-como-o-vox-ai-evoluiu-de-planilhas-para-uma-arquitetura-escalável-com-supabase-4c51b951ed56
      name: Artigos mais recente no Medium
      
    - icon: material/email
      link: mailto:assistentedeapoiolgbtvox@gmail.com
      name: Contato por E-mail
    
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/5571992348839
      name: Atendimento via WhatsApp

nav:
  - Visão Geral: index.md
  - Estrutura de Pastas e Arquivos: estrutura-do-projeto.md
  - Stack Tecnológica e Ferramentas: stack.md
  - Arquitetura do Sistema: arquitetura.md
  - Banco de Dados: banco-de-dados.md
  - Cálculo Vetorial: calculo-intro.md
  - Módulos do Código: modulos-do-codigo.md
  - CI/CD e Automação: ci-cd.md
  - Sistema de Segurança: sistema-de-seguranca.md
  - Testes Automatizados: testes-automatizados.md
  - Git Cliff: git-cliff.md
  - Scripts Utilitários: scripts-utilitarios.md
  - Convenções do Projeto: convencoes-do-projeto.md
  - Como Rodar Localmente: como-rodar-localmente.md
  - Governança, Ética e Documentos Legais: governanca-etica-docs-legais.md
  - Glossário: glossario.md
  - Links e Recursos Úteis: links-recursos-uteis.md