name: 📜 Deploy da Documentação no MKDocs

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4
        
      - name: Injetar Versão nos arquivos
        run: |
          sed -i "s|Licença GNU GPLv3|Licença GNU GPLv3 \| Versão ${{ github.ref_name }}|g" mkdocs.yml
          sed -E -i "s|(> Última atualização por .* em [0-9]{2}/[0-9]{2}/[0-9]{4})|\1 (Versão ${{ github.ref_name }})|g" docs/index.md
          
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - name: Instalar MkDocs
        run: pip install -r requirements.txt
        
      - name: Publicar no GitHub Pages
        run: mkdocs gh-deploy --force